# Generated by Django 5.1 on 2025-03-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isbn',
            field=models.CharField(default='9783161484100', max_length=13),
        ),
    ]
