# Generated by Django 5.1 on 2025-03-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isbn',
            field=models.CharField(default='9781108988234', max_length=13),
        ),
    ]
